### model
model_name_or_path: /home/xiaopeng_ye/LLMs/Meta-Llama-3-8B-Instruct
reward_model: saves/llama3-8b/lora/reward
quantization_bit: 4

### method
stage: ppo
do_train: true
finetuning_type: lora
lora_target: all
#deepspeed: /home/xiaopeng_ye/experiment/Agent4Fairness/LLaMA-Factory/examples/deepspeed/ds_z0_config.json #examples/deepspeed/ds_z3_config.json

### dataset
dataset: fairagent   #identity,alpaca_en_demo  #
template: llama3
cutoff_len: 4096 #1024  #
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 4  #16

### output
output_dir: saves/llama3-8b/lora/ppo
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
optim: paged_adamw_8bit
learning_rate: 1.0e-5   #1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000

### generate
max_new_tokens: 4096  #16384
top_k: 0
top_p: 0.9

#report_to: wandb
#run_name: test_run
max_length: 4096  #16384